def queueId(id):

    switch = {
            0: 'Custom Game',
            72: 'Howling Abyss',
            73: 'Howling Abyss',
            75: 'Hexakill',
            76: 'URF',
            78: 'Howling Abyss',
            83: 'URF AI',
            98: 'TT hexa',
            100: 'ARAM',
            310: 'Nemesis',
            313: 'Black market',
            317: 'Crystal scar',
            325: 'SR ARAM',
            400: 'SR draft pick',
            420: 'SR Solo ranked',
            430: 'SR blind pick',
            440: 'SR Flex',
            450: 'Howling abyss Aram',
            460: 'TT blind',
            470: 'TT flex',
            600: 'SR blood hunt',
            610: 'Dark star',
            700: 'Clash',
            800: 'TT co-op',
            810: 'TT co-op',
            820: 'TT co-op',
            830: 'SR co-op',
            840: 'SR co-op',
            850: 'SR co-op',
            900: 'SR ARURF',
            910: 'Ascension',
            920: 'Legend of the poro king',
            940: 'Nexus siege',
            950: 'SR Doom bots',
            960: 'SR Doom bots',
            980: 'Star guardian',
            990: 'Star guardian',
            1000: 'Project: hunter game',
            1010: 'Snow ARURF',
            1020: 'SR one for all',
            1030: 'Odyssey',
            1040: 'Odyssey',
            1050: 'Odyssey',
            1060: 'Odyssey',
            1070: 'Odyssey',
            1200: 'Nexus blitz'
    }
    return switch.get(id)
